name: Build docker image
on:
  # run it on push when a tag is released
  push:
    tags:
      - "*"

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV    
      
      - name: Build image and push python 3.8 version to Docker Hub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
              satel/python-base:${{env.RELEASE_VERSION}}-python3.8
          build-args: |
              IMAGE_VERSION=python:3.8.12-slim
              REQUIREMENTS_VERSION=3.8
          push: true
      
      - name: Build image and push python 3.9 version to Docker Hub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
              satel/python-base:${{env.RELEASE_VERSION}}-python3.9
          build-args: |
              IMAGE_VERSION=python:3.9.6-slim
              REQUIREMENTS_VERSION=3.9
          push: true
      
      - name: Build image and push python 3.10 version to Docker Hub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
              satel/python-base:${{env.RELEASE_VERSION}}-python3.10
          build-args: |
              IMAGE_VERSION=python:3.10.0-slim
              REQUIREMENTS_VERSION=3.10
          push: true
